"""add telegramuser and crd model

Revision ID: 576308ee3c00
Revises: 33aae2df2680
Create Date: 2025-08-14 09:27:40.385790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576308ee3c00'
down_revision: Union[str, Sequence[str], None] = '33aae2df2680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('chat_id', sa.String(length=50), nullable=True))
    op.add_column('order', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('order', sa.Column('username', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('order_user_fkey'), 'order', type_='foreignkey')
    op.drop_column('order', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('order_user_fkey'), 'order', 'telegramuser', ['user'], ['id'])
    op.drop_column('order', 'username')
    op.drop_column('order', 'full_name')
    op.drop_column('order', 'chat_id')
    # ### end Alembic commands ###
