"""add telegramuser and crd model

Revision ID: 5dcd957fc1e7
Revises: 8ec91548b7bb
Create Date: 2025-08-20 18:05:50.475782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dcd957fc1e7'
down_revision: Union[str, Sequence[str], None] = '8ec91548b7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegramuser', sa.Column('is_purchase', sa.Boolean(), nullable=True))
    op.add_column('telegramuser', sa.Column('purchase_data', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegramuser', 'purchase_data')
    op.drop_column('telegramuser', 'is_purchase')
    # ### end Alembic commands ###
