"""add telegramuser and crd model

Revision ID: 6efeff2c7d1d
Revises: b0fd12bd8de8
Create Date: 2025-08-21 17:05:10.515821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efeff2c7d1d'
down_revision: Union[str, Sequence[str], None] = 'b0fd12bd8de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegramuser', sa.Column('day', sa.Integer(), nullable=True))
    op.add_column('telegramuser', sa.Column('card_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegramuser', 'card_ids')
    op.drop_column('telegramuser', 'day')
    # ### end Alembic commands ###
