"""add telegramuser and crd model

Revision ID: 6f6f6b3324ce
Revises: 5dcd957fc1e7
Create Date: 2025-08-20 18:06:37.299186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6f6b3324ce'
down_revision: Union[str, Sequence[str], None] = '5dcd957fc1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
