"""add boolean field on telegramusers

Revision ID: 8c7051640cf6
Revises: 576308ee3c00
Create Date: 2025-08-19 13:53:15.762070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7051640cf6'
down_revision: Union[str, Sequence[str], None] = '576308ee3c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegramuser', sa.Column('is_diller', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegramuser', 'is_diller')
    # ### end Alembic commands ###
