"""add status fielad on telegram

Revision ID: 8ec91548b7bb
Revises: 8c7051640cf6
Create Date: 2025-08-20 17:45:42.462073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec91548b7bb'
down_revision: Union[str, Sequence[str], None] = '8c7051640cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegramuser', sa.Column('status_adverb', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegramuser', 'status_adverb')
    # ### end Alembic commands ###
