"""add telegramuser and crd model

Revision ID: b0fd12bd8de8
Revises: 6f6f6b3324ce
Create Date: 2025-08-20 18:06:40.776698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0fd12bd8de8'
down_revision: Union[str, Sequence[str], None] = '6f6f6b3324ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
